FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD employee.jar /opt/employee/
EXPOSE 8080
WORKDIR /opt/employee/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "employee.jar"]
